config/routes.rb
Rails.application.routes.draw do
  root 'event#index' #page d'accueil = get 'event/index', to: 'event#index'
  
  get 'event/secret', to: 'event#secret'
  devise_for :users#,controllers: { registrations: "registrations"
  resources :events
end


# events#new
#   si pas connecté
# registrations#new
# sessions#new
#   si connecté
# users#show
# sessions#destroy

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
# validates :start_date, presence: true
# validates :start_must_be_future
# validates :duration, presence: true, numericality: { only_integer: true, greater_than: 0 } #le nombre de minutes doit être un multiple de 5, et est strictement positif
# validates :duration_must_be_multiple_of_5
# validates :title, presence: true, length: { in: 5..140 } #doit faire au moins 5 caractères et maxi 140 caractères.
# validates :description, presence: true, length: { in: 20..1000 }
# validates :price, presence: true, numericality: { only_integer: true, greater_than: 1, less_than_or_equal_to: 1000 }
# validates :location, presence: true

belongs_to :admin, class_name: 'User' # = administrateur (utilisateur)

has_many :participations, dependent: :destroy#Un événement a plusieurs participations
has_many :attendees, through: :participations, class_name: 'User' #plusieurs participants (utilisateurs) au travers des participations
end
# private
# ​
#   #Valider que la date de début est bien dans le futur
#   def start_must_be_future
#     return if start_date.blank? #On sort de la boucle si start_date est vide
# ​
#     if start_date < Time.now
#       errors.add(:start_date, "cannot be past")
#     end
#   end
# ​
#   #Duration is multiple of 5
#   def duration_must_be_multiple_of_5
#     return if duration.blank? #On sort si la fonction est vide
# ​
#     if duration % 5 != 0
#       errors.add(:duration, "Duration has to be multiple of 5")
#     end
# ​
#   end

app/models/participation.rb
class Participation < ApplicationRecord
belongs_to :event
belongs_to :attendee, class_name: "User"
 # after_create :new_participant_email
 #
 # def new_participant_email
 #   ParticipationMailer.new_participant_email(self.participant,self.event).deliver_now
 # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

      has_many :events, foreign_key: 'admin_id', class_name: "Event", dependent: :destroy
        has_many :participations, foreign_key: 'attendee_id', class_name: "Participation", dependent: :destroy
        has_many :events, through: :participations

        # after_create :welcome_send
        #
        # def welcome_send
        #   UserMailer.welcome_email(self).deliver_now
        # end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_controller.rb
class EventController < ApplicationController
before_action :authenticate_user!, only: [:secret]

def secret
end

def new
  @event = Event.new
end

def create
  @event = Event.new(event_params)
  @event.admin_id = current_user.id
  if @event.save
    redirect_to event_path(@event)
    flash[:success] = 'Your event is created'
  else flash[:danger] = 'Your event is not create, please try again'
       render 'new'
  end
end

def show
  @event = Event.find(params[:id])
end

def index
  @events = Event.all
end

def edit
  @event = Event.find(params[:id])
end

def update
  @event = Event.find(params[:id])
  if @event.update(event_params)
    redirect_to event_path(@event)
  else redirect_to event_path(@event)
       flash[:error] = 'YOUR EVENT IS NOT UPDATED. Please try again and make sure to update all the field.'
  end
end

def destroy
  @event = Event.find(params[:id])
  @event.destroy
  redirect_to user_path(current_user)
end

def subscribe
  @event = Event.find(params[:event_id])

  @amount = @event.price_cents
  customer = Stripe::Customer.create(
    email: params[:stripeEmail],
    source: params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    customer: customer.id,
    amount: @amount,
    description: 'Rails Stripe customer',
    currency: 'eur'
  )

  @event.attendees << current_user
  redirect_to @event
  flash[:success] = 'You are now attending this event'
rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to @event
end

def unsubscribe
  @event = Event.find(params[:event_id])
  @event.attendees.delete(current_user)
  redirect_to user_path(current_user)
  flash[:danger] = 'You are no longer attending this event'
end

private

def event_params
  params.require(:event).permit(:description, :date, :place, :price)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/views/event/index.html.erb
<div class="jumbotron jumbotron-fluid jumbotron-hero">
  <div class='container'>
    <div class="text-center">
    <br>
    <br>
    <br>
    <br>
    <h1>WELCOME ON EVENBRIT<h1>
      <h5>All events in your city</h5>
    <br>
    <br>
    <br> 
      <% if user_signed_in? %>
        <div class="text-center">
        
          <p>Voici ton email : <%= current_user.email %></p>
     
          <%= link_to "Edit email / password", edit_user_registration_path, class:'btn btn-outline-dark rounded-pill' %>

          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:'btn btn-outline-dark rounded-pill' %>
          
    ​    </div>
          <br>
          <br>
      <% else %>

          <%= link_to "Sign in", new_user_session_path, class:'btn btn-1 btn-lg rounded-pill'%>
          <%= link_to "Sign up", new_user_registration_path, class:'btn btn-2 btn-lg rounded-pill' %>
          <br>
          <br>
        <% end %>
        <div class='container'>
          <div class="card-columns">
          <% @events.each do |event| %>
            <div class="card">
              <div class="card-body">
                  <h4 class="card-title"><%= link_to event.title, event_path(event) %></h4>
                  <p class="card-text"><%= truncate(event.description, length: 100) %></p>
                  <% unless event[:admin_id] != event.admin_id %>
                  <p> <%= link_to "Edit", edit_event_path(event), class: "btn btn-3 rounded-pill" %> 
                      <%= link_to "Delete", event_path(event), method: :delete, data: { confirm: "Are you sure you want to delete this event?"}, class:"btn btn-4 rounded-pill" %>   
                  </p> 
                  <% end %>
              </div>
            </div>
          <% end %>
          </div>
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Evenbrite</title>
    <link rel="icon" type="image/png" href="/assets/E.png">
    <link rel="stylesheet" href="style.css">
    <script src="https://kit.fontawesome.com/8813a93217.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Anton|Staatliches|Varela+Round&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
</body>
  </head>

  <body>  
  <div class="d-flex flex-column flex-md-row align-items-center px-md-4 bg-white">
    <a class="mr-md-auto navbar-brand" href="<%= root_path %>" title="Home"><img style="max-width:50px;" src="/assets/E.png"></a>
    
    <nav class="my-2 my-md-0 mr-md-10">
        <a href="<%= root_path %>" class ="btn btn-outline rounded-pill">Home</a>
        <a href="#" class ="btn btn-outline rounded-pill">New Event</a>
        <a href="#" class ="btn btn-outline rounded-pill">Profile</a>
        
      <button class="btn btn-outline-dark rounded-pill dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Menu
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a href="<%= new_user_session_path %>" class="dropdown-item">Log in</a>
        <a href="<%= edit_user_registration_path %>" class="dropdown-item">Edit Profile</a>
        <a href="<%= new_user_registration_path %>" class="dropdown-item">Sign Up</a>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class:'dropdown-item' %>
      </div>

    </nav>
  </div>
  <%= yield %>
  </body>

  <div style="text-align: center; font-size: 20px">
  <footer class="container">
      <div class="row">
          <div class="col-12 col-md">
              <img class="mb-2" src="/docs/4.3/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
              <small class="d-block mb-3 text-grey">Copyright © 2019 Evenbrit. All rights reserved.</small>
          </div>
      </div>
  </footer>
  </div>

</html>